spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smartfinance
    username: postgres
    password: Abdul@786
  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration



app:
  jwt:
    secret: soWTCqUj+CNC76IP5MILdHQeizaGzIv8LHc1zzdIF+o=
    access-token-expiration: 900000
    refresh-token-expiration: 604800000
    issuer: smart-finance-api


stock:
  api:
    key: d938921r01qq79pbk05gd938921r01qq79pbk060
    base-url: https://finnhub.io/api/v1

